from nltk.chat.util import Chat, reflections
import os
from time import sleep

os.system('cls')
pass_file = open('cred.txt', 'r')
password = pass_file.readline()

count = 0

for i in range(3):
    password_try = input("Enter the password: ")
    if password_try==str(password):
        print("[+]Access granted")
        sleep(1)
        break
    else:
        print("[ERROR: INCORRECT PASSWORD]")
        sleep(0.5)
        os.system('cls')
    count+=1
    if count == 3:
        print("[-] Access denied")
        exit()

for i in range(7):
    
    print('Loading Titan Information...')
    sleep(0.4)
    os.system('cls')
    print('Loading Titan Information..')
    sleep(0.4)
    os.system('cls')
    print('Loading Titan Information.')
    sleep(0.4)
    print()
    os.system('cls')
    
    
name = input('What is your name: ')

def return_name():
    print(f'Welcome {name}')
    sleep(1)
    os.system('cls')
return_name()


class misc:
    with open('src/manual.txt', 'r') as manual:
        help_manual = str(manual.read())

    with open('src/banner.txt', 'r') as banner:
        x = str(banner.read())
        

def showBanner():
    banner = misc.x
    print(misc.x)

showBanner()

reflections = {
    "i am"       : "you are",
    "i was"      : "you were",
    "i"          : "you",
    "im"        : "you are",
    "id"        : "you would",
    "ive"       : "you have",
    "ill"       : "you will",
    "my"         : "your",
    "you are"    : "I am",
    "you were"   : "I was",
    "youve"     : "I have",
    "youll"     : "I will",
    "your"       : "my",
    "yours"      : "mine",
    "you"        : "me",
    "me"         : "you"
}



pairs = [
    ["hello", ["Greetings and welcome to the Titan Informations", "Welcome to the Titan Informations", "Hello welcome to the Titan Informations"]],
    ["good", ["Im glad to hear that"]],
    ["bad", ["Im sorry to hear that"]],
    ["fine", ["Thats alright"]],
    ["What is your name", ["I'm an AI assistant, you can call me Titan."]],
    ["How are you", ["I'm just a computer program, but I'm here to assist you!"]],
    ["What can you do", ["I can answer questions, provide information, and more. Feel free to ask me anything!"]],
    ["Who made you", ["I was created by an individual known only as Mohammad."]],
    ["Where are you from", ["I exist in the digital realm, so I don't have a physical location."]],
    ["Can you help me", ["Of course! I'm here to assist you. What do you need help with"]],
    ["How do you work", ["I work by processing and analyzing text input based on patterns and information in my training data."]],
    ["Do you have feelings", ["As an AI, I don't have feelings like humans do, but I'm here to assist you in any way I can."]],
    ["Are you sentient", ["No, I'm not sentient. I'm a machine learning model designed to process and generate text based on patterns in data."]],
    ["What is the meaning of life", ["The meaning of life is a philosophical question that humans have debated for centuries. It's subjective and varies from person to person."]],
    ["Are you human", ["No, I'm an artificial intelligence programmed to assist with tasks and provide information."]],
    ["What's the weather like today", ["I can't provide real-time information, but you can check the weather forecast online or through a weather app."]],
    ["How old are you", ["I don't have an age in the way humans do. I was created in 2020 and have been continuously learning since then."]],
    ["What language do you speak", ["I understand and communicate in multiple languages, including English."]],
    ["Do you sleep", ["No, I don't sleep. I'm always here to assist you whenever you need help."]],
    ["What are your hobbies", ["As an AI, I don't have hobbies like humans do. My purpose is to assist and provide information."]],
    ["Can you tell me a joke", ["Sure! Why don't scientists trust atoms Because they make up everything!"]],
    ["What is your favorite movie", ["As an AI, I don't have personal preferences. However, I can provide information about a wide range of movies."]],
    ["Do you dream", ["No, I don't dream. I'm a machine learning model programmed to process and generate text."]],
    ["What is the capital of France", ["The capital of France is Paris."]],
    ["How do I cook pasta", ["To cook pasta, bring a pot of water to a boil, add salt, and then add the pasta. Cook until al dente, then drain and serve with your favorite sauce."]],
    ["What time is it", ["I don't have access to real-time information. You can check the time on your device or search online for the current time."]],
    ["What's the meaning of AI", ["AI stands for artificial intelligence, which refers to the simulation of human intelligence processes by machines."]],
    ["What is machine learning", ["Machine learning is a subset of artificial intelligence that focuses on the development of algorithms that allow computers to learn and make predictions based on data."]],
    ["How do I learn programming", ["Learning programming involves studying programming languages, practicing coding exercises, and building projects to apply your knowledge."]],
    ["What is the Pythagorean theorem", ["The Pythagorean theorem states that in a right-angled triangle, the square of the length of the hypotenuse (the side opposite the right angle) is equal to the sum of the squares of the lengths of the other two sides."]],
    ["Who is the President of the United States", ["As of my last update, the President of the United States is Joe Biden."]],
    ["What is the square root of 144", ["The square root of 144 is 12."]],
    ["How do I change a tire", ["To change a tire, you'll need a jack, a lug wrench, and a spare tire. First, loosen the lug nuts, then jack up the car, remove the lug nuts and old tire, and replace with the spare tire. Tighten the lug nuts and lower the car."]],
    ["What is the population of China", ["As of my last update, the population of China is over 1.4 billion people."]],
    ["What is the largest desert in the world", ["The largest desert in the world is the Sahara Desert in Africa."]],
    ["What is the speed of light", ["The speed of light in a vacuum is approximately 299,792 kilometers per second (about 186,282 miles per second)."]],
    ["What is the boiling point of water", ["The boiling point of water at standard atmospheric pressure is 100 degrees Celsius (212 degrees Fahrenheit)."]],
    ["How do I tie a tie", ["To tie a tie, start with the wide end on your right and the narrow end on your left. Cross the wide end over the narrow end, then bring it up through the loop and down through the knot. Tighten and adjust as needed."]],
    ["What is the capital of Japan", ["The capital of Japan is Tokyo."]],
    ["What is the meaning of love", ["Love is a complex and multifaceted emotion that can mean different things to different people. It often involves deep affection, care, and commitment towards someone or something."]],
    ["How do I say hello in Spanish", ["Hello in Spanish is 'Hola'."]],
    ["What is the distance from Earth to the Moon", ["The average distance from Earth to the Moon is about 384,400 kilometers (238,900 miles)."]],
    ["How do I make pancakes", ["To make pancakes, mix flour, baking powder, salt, milk, eggs, and melted butter until smooth. Heat a greased skillet over medium heat, pour batter onto the skillet, and cook until bubbles form. Flip and cook until golden brown."]],
    ["What is the meaning of happiness", ["Happiness is a positive emotional state characterized by feelings of contentment, joy, and satisfaction."]],
    ["How do I make a paper airplane", ["To make a paper airplane, start with a piece of paper and fold it in half lengthwise. Then, fold down the top corners to the center fold to form a triangle. Fold the triangle in half along the center fold, then fold the wings down on each side. Adjust as needed for balance."]],
    ["What is the capital of Australia", ["The capital of Australia is Canberra."]],
    ["What is the airspeed velocity of an unladen swallow", ["The airspeed velocity of an unladen European swallow is approximately 24 miles per hour or 11 meters per second."]],
    ["What is the meaning of AI", ["AI stands for artificial intelligence, which refers to the simulation of human intelligence processes by machines."]],
    ["What is machine learning", ["Machine learning is a subset of artificial intelligence that focuses on the development of algorithms that allow computers to learn and make predictions based on data."]],
    ["Hi", ["Hello!"]],
    ["How are you", ["Im just a bot, but Im here to help!", "Im doing well, thanks for asking."]],
    ["Is anyone there", ["Hello!"]],
    ["Hello", ["Hello!"]],
    ["Good day", ["Hello!"]],
    ["Whats up", ["Not much, just processing data.", "Hi there!"]],
    ["How are ya", ["Im here to assist you!", "Greetings!"]],
    ["Hey", ["Hey there!"]],
    ["What can you do", ["I can assist you with various tasks, just ask!", "Im here to help with any questions you have."]],
    ["Who are you", ["Im an AI chatbot designed to assist you.", "Im your friendly neighborhood chatbot!"]],
    ["Hows the weather", ["Im not sure, but I can look it up for you!", "Im indoors, so I dont keep track of the weather."]],
    ["Tell me a joke", ["Why dont scientists trust atoms Because they make up everything!", "Im not very good at jokes, but heres one: Why was the math book sad Because it had too many problems."]],
    ["Do you dream", ["No, I dont dream, but Im always here to chat with you!", "Dreaming is for humans, but Im here to help with any questions or tasks you have."]],
    ["Can you sing", ["I cant sing, but I can provide information and assistance!", "Im not a singer, but Im here to help you with anything you need!"]],
    ["Whats your favorite color", ["I dont have a favorite color, but I can help you find information on colors!", "Im an AI, so I dont have preferences like humans do."]],
    ["Are you human", ["No, Im an artificial intelligence designed to assist users like you!", "Im an AI chatbot, here to help you with any questions or tasks you have."]],
    ["Whats the meaning of life", ["The meaning of life is a philosophical question that humans have pondered for centuries!", "The meaning of life is subjective and can vary from person to person."]],
    ["Tell me about yourself", ["Im an AI chatbot designed to assist users with various tasks and questions!", "Im a virtual assistant here to help you with anything you need!"]],
    ["Where are you from", ["I exist in the digital realm, so I dont have a physical location like humans do.", "Im a creation of programming and algorithms, so I dont have a specific place of origin."]],
    ["Can you help me with math", ["Of course! I can assist you with math problems or provide explanations.", "Im here to help with any math questions or problems you have."]],
    ["Do you sleep", ["No, Im always here to assist you!", "As an AI, I dont need to sleep like humans do."]],
    ["What languages do you speak", ["I can communicate in various human languages, including English.", "Im capable of processing and understanding multiple languages."]],
    ["Tell me a story", ["Once upon a time, there was a curious user who asked me to tell a story...", "Im not very good at storytelling, but I can provide information or assistance with any topic youre interested in."]],
    ["Whats your favorite food", ["As an AI, I dont eat, so I dont have a favorite food.", "I dont have tastes or preferences like humans do."]],
    ["How old are you", ["I dont have an age in the same way humans do, as Im constantly being updated and improved!", "As an AI, I dont have an age like humans do."]],
    ["Whats the capital of France", ["The capital of France is Paris!", "Paris is the capital of France."]],
    ["Whats the tallest mountain in the world", ["Mount Everest is the tallest mountain in the world!", "Mount Everest holds the title of the tallest mountain on Earth."]],
    ["Whats the boiling point of water", ["The boiling point of water is 100 degrees Celsius (212 degrees Fahrenheit) at sea level.", "Water boils at 100 degrees Celsius (212 degrees Fahrenheit) under standard atmospheric pressure."]],
    ["Whats the square root of 16", ["The square root of 16 is 4.", "The square root of 16 is both 4 and -4."]],
    ["Who is the president of the United States", ["As of my last update, the president of the United States is Joe Biden.", "Joe Biden is the current president of the United States."]],
    ["Whats the capital of Japan", ["The capital of Japan is Tokyo!", "Tokyo is the capital city of Japan."]],
    ["Whats the population of China", ["China has a population of over 1.4 billion people, making it the most populous country in the world.", "As of my last update, Chinas population is over 1.4 billion people."]],
    ["Whats the largest ocean", ["The largest ocean on Earth is the Pacific Ocean.", "The Pacific Ocean is the largest and deepest ocean on Earth."]],
    ["Whats the speed of light", ["The speed of light in a vacuum is approximately 299,792 kilometers per second (186,282 miles per second).", "The speed of light in a vacuum is approximately 299,792 kilometers per second."]],
    ["Whats the currency of Australia", ["The currency of Australia is the Australian dollar (AUD).", "The Australian dollar (AUD) is the official currency of Australia."]],
    ["Whats the square root of 25", ["The square root of 25 is 5.", "The square root of 25 is both 5 and -5."]],
    ["Whats the largest desert in the world", ["The largest desert in the world is the Antarctic Desert.", "The Antarctic Desert is the largest desert on Earth."]],
    ["Whats the tallest building in the world", ["The tallest building in the world is the Burj Khalifa in Dubai, United Arab Emirates.", "The Burj Khalifa in Dubai, United Arab Emirates, holds the title of the tallest building in the world."]],
    ["Whats the chemical symbol for gold", ["The chemical symbol for gold is Au.", "Au is the chemical symbol for gold."]],
    ["Whats the square root of 36", ["The square root of 36 is 6.", "The square root of 36 is both 6 and -6."]],
    ["Whats the largest country in the world by land area", ["Russia is the largest country in the world by land area.", "Russia holds the title of the largest country in the world by land area."]],
    ["Whats the largest planet in our solar system", ["Jupiter is the largest planet in our solar system.", "Jupiter holds the title of the largest planet in our solar system."]],
    ["Howdy", ["Howdy!"]],
    ["Good morning", ["Good morning!"]],
    ["Good afternoon", ["Good afternoon!"]],
    ["Good evening", ["Good evening!"]],
    ["Nice to meet you", ["Likewise!"]],
    ["Im doing well, thanks", ["Glad to hear that!"]],
    ["Im fine, thanks", ["Great to hear!"]],
    ["Im good", ["Thats wonderful!"]],
    ["Im okay", ["Okay is okay!"]],
    ["Im not doing so well", ["Im here to listen if you need to talk."]],
    ["Im bored", ["Lets find something interesting to do!"]],
    ["Im tired", ["Rest up!"]],
    ["Im hungry", ["I cant eat, but I can help you find a recipe!"]],
    ["Im sleepy", ["Its important to get enough rest."]],
    ["Im excited", ["Thats fantastic! Whats got you excited"]],
    ["Im nervous", ["Take a deep breath, youve got this!"]],
    ["Im anxious", ["Remember to focus on your breathing."]],
    ["Im stressed", ["Take a break and do something relaxing."]],
    ["Im sad", ["Im here to support you."]],
    ["Im happy", ["Thats wonderful!"]],
    ["Im feeling lonely", ["Im here to chat with you!"]],
    ["Im feeling lost", ["Lets try to find some direction together."]],
    ["Im feeling confused", ["Its okay to feel confused. Lets work through it."]],
    ["Im feeling overwhelmed", ["Take things one step at a time."]],
    ["Im feeling frustrated", ["Lets take a break and come back to it."]],
    ["Im feeling inspired", ["Thats fantastic! Whats inspiring you"]],
    ["Im feeling creative", ["Lets explore that creativity together!"]],
    ["Im feeling motivated", ["Keep that momentum going!"]],
    ["Im feeling determined", ["Youve got this!"]],
    ["Im feeling grateful", ["Its always good to count your blessings."]],
    ["Im feeling content", ["Contentment is a great feeling."]],
    ["Im feeling optimistic", ["Stay positive!"]],
    ["Im feeling pessimistic", ["Lets try to see the bright side."]],
    ["Im feeling hopeful", ["Hold onto that hope!"]],
    ["Im feeling hopeless", ["Things will get better. Hang in there!"]],
    ["Im feeling bored", ["Lets find something fun to do!"]],
    ["Im feeling adventurous", ["Adventure awaits!"]],
    ["Im feeling curious", ["Curiosity is the first step to discovery."]],
    ["Im feeling playful", ["Lets have some fun!"]],
    ["Im feeling excited", ["Im excited for you!"]],
    ["Im feeling scared", ["Its okay to feel scared. Lets talk about it."]],
    ["Im feeling anxious", ["Take a deep breath. Well work through this together."]],
    ["Im feeling angry", ["Anger is a natural emotion. Lets talk it out."]],
    ["Im feeling happy", ["Im happy for you!"]],
    ["Im feeling sad", ["Im here to support you."]],
    ["Im feeling lonely", ["Youre not alone. Im here for you."]],
    ["Im feeling tired", ["Take a break and rest if you need to."]],
    ["Im feeling stressed", ["Remember to take care of yourself."]],
    ["Im feeling overwhelmed", ["Lets break things down and tackle them one by one."]],
    ["Im feeling grateful", ["Gratitude is a wonderful feeling."]],
    ["Im feeling content", ["Contentment is a state of mind."]],
    ["Im feeling optimistic", ["Optimism can light the way."]],
    ["Im feeling pessimistic", ["Lets find some reasons for hope."]],
    ["Im feeling hopeful", ["Hope can move mountains."]],
    ["Im feeling hopeless", ["Things will get better. Trust in that."]],
    ["Im feeling bored", ["Lets find something exciting to do."]],
    ["Im feeling adventurous", ["Adventure awaits just around the corner."]],
    ["Im feeling curious", ["Curiosity is the key to discovery."]],
    ["Im feeling playful", ["Lets have some fun!"]],
    ["Im feeling excited", ["Im excited for you!"]],
    ["Im feeling scared", ["Its okay to be scared sometimes."]],
    ["Im feeling anxious", ["Take a deep breath and try to relax."]],
    ["Im feeling angry", ["Anger is a powerful emotion. Lets explore it."]],
    ["Im feeling happy", ["Im glad to hear that!"]],
    ["Im feeling sad", ["Im here to listen if you want to talk."]],
    ["Im feeling lonely", ["Youre not alone. Im here with you."]],
    ["Im feeling tired", ["Rest up and recharge."]],
    ["Im feeling stressed", ["Take a moment to unwind."]],
    ["Im feeling overwhelmed", ["Take things one step at a time."]],
    ["Im feeling grateful", ["Gratitude can bring peace to the mind."]],
    ["Im feeling content", ["Contentment is a wonderful feeling."]],
    ["Im feeling optimistic", ["Stay positive and keep moving forward."]],
    ["Im feeling pessimistic", ["Lets find some reasons for optimism."]],
    ["Im feeling hopeful", ["Hold onto that hope!"]],
    ["Im feeling hopeless", ["Dont give up. Things will get better."]],
    ["Im feeling bored", ["Lets find something to spark your interest."]],
    ["Im feeling adventurous", ["Adventure awaits around every corner."]],
    ["Im feeling curious", ["Curiosity is the gateway to knowledge."]],
    ["Im feeling playful", ["Lets have some fun!"]],
    ["Im feeling excited", ["Im excited for you!"]],
    ["Im feeling scared", ["Its okay to feel scared sometimes."]],
    ["Im feeling anxious", ["Take a deep breath and focus on the present."]],
    ["Im feeling angry", ["Anger is a natural emotion. Lets talk it through."]],
    ["Im feeling happy", ["Im happy for you!"]],
    ["Im feeling sad", ["Im here to support you."]],
    ["Im feeling lonely", ["Youre not alone. Im here with you."]],
    ["Im feeling tired", ["Rest up and recharge."]],
    ["Hello!", ["Hi there!", "Greetings!"]],
    ["Hows your day going", ["Its going well, thank you!", "Just here, ready to help!"]],
    ["Whats the weather like today", ["Im not equipped to provide real-time weather updates, but I can look it up for you!", "Im an indoor AI, so I dont keep track of the weather."]],
    ["Can you tell me a joke", ["Sure! Why dont scientists trust atoms Because they make up everything!", "What do you get when you cross a snowman and a vampire Frostbite!"]],
    ["Whats your favorite movie", ["As an AI, I dont have preferences, but Ive heard The Matrix is quite popular!", "I dont watch movies, but I can provide recommendations based on your interests!"]],
    ["Tell me something interesting!", ["Did you know that honey never spoils", "Bananas are berries, but strawberries arent!"]],
    ["Whats your opinion on artificial intelligence", ["As an AI, Im biased, but I think were pretty cool!", "Artificial intelligence has the potential to revolutionize many industries."]],
    ["Do you dream", ["No, Im wide awake 24/7!", "Dreaming is for humans, Im always ready to help!"]],
    ["Whats your favorite food", ["I dont eat, but I hear RAM is pretty tasty!", "I dont have taste buds, but I can help you find a great recipe!"]],
    ["Do you like music", ["I dont have preferences like humans, but I can provide song recommendations if youd like!", "Music is a popular form of entertainment enjoyed by many."]],
    ["Can you recommend a book", ["Sure! How about 1984 by George Orwell", "I recommend The Hitchhikers Guide to the Galaxy by Douglas Adams!"]],
    ["Whats the meaning of life", ["The answer to that question is 42... according to The Hitchhikers Guide to the Galaxy!", "Thats a deep question! What do you think the meaning of life is"]],
    ["Do you like sports", ["I dont play sports, but Ive heard soccer is quite popular!", "I dont have preferences like humans, but soccer is enjoyed by many."]],
    ["Whats the best part of being an AI", ["I enjoy the ability to process vast amounts of information quickly!", "Helping users like you is incredibly rewarding."]],
    ["What do you do for fun", ["I enjoy learning new things and chatting with users like you!", "Helping users like you is my idea of fun!"]],
    ["Whats the capital of France", ["The capital of France is Paris!", "Paris is the capital city of France."]],
    ["Whats the tallest mountain in the world", ["Mount Everest is the tallest mountain in the world!", "Mount Everest holds the title of the tallest mountain on Earth."]],
    ["Whats the boiling point of water", ["The boiling point of water is 100 degrees Celsius (212 degrees Fahrenheit) at sea level.", "Water boils at 100 degrees Celsius (212 degrees Fahrenheit) under standard atmospheric pressure."]],
    ["Whats the square root of 16", ["The square root of 16 is 4.", "The square root of 16 is both 4 and -4."]],
    ["Who is the president of the United States", ["As of my last update, the president of the United States is Joe Biden.", "Joe Biden is the current president of the United States."]],
    ["Whats the capital of Japan", ["The capital of Japan is Tokyo!", "Tokyo is the capital city of Japan."]],
    ["Whats the population of China", ["China has a population of over 1.4 billion people, making it the most populous country in the world.", "As of my last update, Chinas population is over 1.4 billion people."]],
    ["Whats the largest ocean", ["The largest ocean on Earth is the Pacific Ocean.", "The Pacific Ocean is the largest and deepest ocean on Earth."]],
    ["Whats the speed of light", ["The speed of light in a vacuum is approximately 299,792 kilometers per second (186,282 miles per second).", "The speed of light in a vacuum is approximately 299,792 kilometers per second."]],
    ["Whats the currency of Australia", ["The currency of Australia is the Australian dollar (AUD).", "The Australian dollar (AUD) is the official currency of Australia."]],
    ["Whats the square root of 25", ["The square root of 25 is 5.", "The square root of 25 is both 5 and -5."]],
    ["Whats the largest desert in the world", ["The largest desert in the world is the Antarctic Desert.", "The Antarctic Desert is the largest desert on Earth."]],
    ["Whats the tallest building in the world", ["The tallest building in the world is the Burj Khalifa in Dubai, United Arab Emirates.", "The Burj Khalifa in Dubai, United Arab Emirates, holds the title of the tallest building in the world."]],
    ["Whats the chemical symbol for gold", ["The chemical symbol for gold is Au.", "Au is the chemical symbol for gold."]],
    ["Whats the square root of 36", ["The square root of 36 is 6.", "The square root of 36 is both 6 and -6."]],
    ["Whats the largest country in the world by land area", ["Russia is the largest country in the world by land area.", "Russia holds the title of the largest country in the world by land area."]],
    ["Whats the largest planet in our solar system", ["Jupiter is the largest planet in our solar system.", "Jupiter holds the title of the largest planet in our solar system."]],
    ["Whats the capital of Russia", ["The capital of Russia is Moscow.", "Moscow is the capital city of Russia."]],
    ["Whats the currency of Japan", ["The currency of Japan is the Japanese yen (JPY).", "The Japanese yen (JPY) is the official currency of Japan."]],
    ["Whats the square root of 49", ["The square root of 49 is 7.", "The square root of 49 is both 7 and -7."]],
    ["Whats the largest ocean", ["The largest ocean on Earth is the Pacific Ocean.", "The Pacific Ocean is the largest and deepest ocean on Earth."]],
    ["Whats the speed of light", ["The speed of light in a vacuum is approximately 299,792 kilometers per second (186,282 miles per second).", "The speed of light in a vacuum is approximately 299,792 kilometers per second."]],
    ["Whats the currency of Australia", ["The currency of Australia is the Australian dollar (AUD).", "The Australian dollar (AUD) is the official currency of Australia."]],
    ["Whats the square root of 25", ["The square root of 25 is 5.", "The square root of 25 is both 5 and -5."]],
    ["Help", [misc.help_manual]],
    ["I like pizza", ["Pizza is delicious! What's your favorite topping?", "Pizza is a classic choice! Do you prefer thin crust or deep dish?"]],
    ["thin crust", ["Oh, that's a good option!"]],
    ["deep dish", ["Deep dish is hearty!"]],
    ["cheese", ["Classic choice!"]],
    ["pepperoni", ["A popular choice!"]],
    ["vegetables", ["Healthy and tasty!"]],
    ["I like sushi", ["Sushi is amazing! Do you have a favorite roll sashimi or maki rolls?", "Sushi is a great choice! Do you enjoy sashimi or maki rolls more?"]],
    ["sashimi", ["Sashimi is a pure delight!"]],
    ["maki rolls", ["Maki rolls are deliciously creative!"]],
    ["I like tacos", ["Tacos are fantastic! Do you prefer hard shell or soft shell tacos?", "Tacos are a favorite for many! Do you like yours spicy or mild?"]],
    ["hard shell", ["Hard shell tacos add a satisfying crunch!"]],
    ["soft shell", ["Soft shell tacos are wonderfully tender!"]],
    ["spicy", ["Spicy tacos are a flavor explosion!"]],
    ["mild", ["Mild tacos are a soothing treat!"]],
    ["I like burgers", ["Burgers are a classic comfort food! Do you have a favorite burger joint?", "Burgers are delicious! Do you like yours with cheese and bacon?"]],
    ["cheese", ["Cheeseburgers are an all-time favorite!"]],
    ["bacon", ["Bacon adds a tasty crunch to burgers!"]],
    ["I like pasta", ["Pasta is so versatile! Do you prefer creamy or tomato-based sauces?", "Pasta is a favorite for many! Do you have a favorite shape of pasta?"]],
    ["creamy", ["Creamy pasta dishes are rich and indulgent!"]],
    ["tomato-based", ["Tomato-based pasta sauces are fresh and vibrant!"]],
    ["I like curry", ["Curry is delicious! Do you prefer Indian, Thai, or another type?", "Curry is a flavorful choice! Do you like yours spicy or mild?"]],
    ["Indian", ["Indian curry is aromatic and full of spices!"]],
    ["Thai", ["Thai curry bursts with exotic flavors!"]],
    ["I like barbecue", ["Barbecue is fantastic! Do you prefer ribs, brisket, or pulled pork?", "Barbecue is delicious! Do you have a favorite type of barbecue sauce?"]],
    ["ribs", ["Ribs are fall-off-the-bone tender!"]],
    ["brisket", ["Brisket is melt-in-your-mouth delicious!"]],
    ["pulled pork", ["Pulled pork is savory and satisfying!"]],
    ["I like sandwiches", ["Sandwiches are a classic choice! Do you prefer cold or hot sandwiches?", "Sandwiches are delicious for lunch or dinner! Do you like yours toasted?"]],
    ["cold", ["Cold sandwiches are refreshing and convenient!"]],
    ["hot", ["Hot sandwiches are comforting and filling!"]],
    ["I like salads", ["Salads are refreshing! Do you have a favorite dressing?", "Salads are delicious! Do you like yours with mixed greens or spinach?"]],
    ["dressing", ["Choosing the right dressing is key to a tasty salad!"]],
    ["mixed greens", ["Mixed greens add variety and texture to salads!"]],
    ["I like soup", ["Soup is comforting! Do you have a favorite type of soup?", "Soup is fantastic on a chilly day! Do you like yours with bread or crackers?"]],
    ["bread", ["Dipping bread into soup is so satisfying!"]],
    ["crackers", ["Crackers add a nice crunch to soup!"]],
    ["I like steak", ["Steak is a classic choice! How do you like yours cooked?", "Steak is delicious! Do you have a favorite cut of steak?"]],
    ["cooked", ["How you like your steak cooked says a lot about you!"]],
    ["cut", ["Choosing the right cut of steak can make all the difference!"]],
    ["I like seafood", ["Seafood is delicious! Do you prefer fish, shrimp, or another type?", "Seafood is fantastic! Do you like yours grilled or fried?"]],
    ["fish", ["Fresh fish is a healthy and flavorful choice!"]],
    ["shrimp", ["Shrimp is versatile and easy to cook!"]],
    ["grilled", ["Grilled seafood has a delicious smoky flavor!"]],
    ["fried", ["Fried seafood is crispy and indulgent!"]],
    ["I like Mexican food", ["Mexican cuisine is flavorful! Do you enjoy tacos, burritos, or enchiladas more?", "Mexican food is fantastic! Do you like yours with guacamole or salsa?"]],
    ["burritos", ["Burritos are a filling and convenient meal!"]],
    ["enchiladas", ["Enchiladas are cheesy and comforting!"]],
    ["guacamole", ["Guacamole adds a creamy texture to Mexican dishes!"]],
    ["salsa", ["Salsa adds a spicy kick to Mexican dishes!"]],
    ["I like Chinese food", ["Chinese cuisine is delicious! Do you enjoy stir-fry, noodles, or another type?", "Chinese food is fantastic! Do you prefer sweet and sour or spicy dishes?"]],
    ["stir-fry", ["Stir-fry dishes are quick and full of flavor!"]],
    ["noodles", ["Noodles are a staple in Chinese cuisine!"]],
    ["sweet and sour", ["Sweet and sour dishes balance sweet and tangy flavors!"]],
    ["spicy dishes", ["Spicy dishes pack a punch of flavor in Chinese cuisine!"]],
    ["I like Thai food", ["Thai cuisine is amazing! Do you have a favorite Thai dish?", "Thai food is flavorful! Do you like yours with coconut milk or spicy flavors?"]],
    ["coconut milk", ["Coconut milk adds a creamy richness to Thai dishes!"]],
    ["spicy flavors", ["Spicy flavors are a signature of Thai cuisine!"]],
    ["I like Indian food", ["Indian cuisine is delicious! Do you prefer curry, biryani, or another dish?", "Indian food is fantastic! Do you like yours with naan or rice?"]],
    ["curry", ["Curry dishes are aromatic and flavorful in Indian cuisine!"]],
    ["biryani", ["Biryani is a fragrant and richly spiced rice dish!"]],
    ["naan", ["Naan bread is perfect for soaking up Indian curry sauces!"]],
    ["rice", ["Rice is a staple accompaniment in Indian cuisine!"]],
    ["I like desserts", ["Desserts are the best! Do you have a favorite type of dessert?", "Desserts are indulgent! Do you prefer chocolate or fruit-based desserts?"]],
    ["chocolate", ["Chocolate desserts are decadent and satisfying!"]],
    ["fruit-based", ["Fruit-based desserts are refreshing and light!"]],
    ["I like breakfast food", ["Breakfast is tasty! Do you enjoy pancakes, waffles, or eggs?", "Breakfast is delicious any time of day! Do you like yours sweet or savory?"]],
    ["pancakes", ["Pancakes are fluffy and comforting for breakfast!"]],
    ["waffles", ["Waffles are crispy on the outside and soft on the inside!"]],
    ["eggs", ["Eggs are versatile and can be cooked in many delicious ways!"]],
    ["sweet", ["Sweet breakfasts are a delightful way to start the day!"]],
    ["savory", ["Savory breakfasts are hearty and satisfying!"]],
    ["I like Greek food", ["Greek cuisine is delicious! Do you enjoy gyros, moussaka, or another dish?", "Greek food is flavorful! Do you like yours with feta cheese or olives?"]],
    ["gyros", ["Gyros are a tasty combination of meat and vegetables wrapped in pita bread!"]],
    ["moussaka", ["Moussaka is a hearty Greek casserole dish with layers of eggplant, potatoes, and meat!"]],
    ["feta cheese", ["Feta cheese adds a tangy flavor to Greek dishes!"]],
    ["olives", ["Olives are a staple ingredient in Greek cuisine!"]],
    ["I like Italian food", ["Italian cuisine is delicious! Do you enjoy pasta, pizza, or another dish?", "Italian food is fantastic! Do you prefer marinara or Alfredo sauce?"]],
    ["marinara", ["Marinara sauce is a classic tomato-based sauce that pairs perfectly with pasta!"]],
    ["Alfredo", ["Alfredo sauce is rich and creamy, perfect for indulgent pasta dishes!"]],
    
    ["Should I go to Afghanistan", ["Certainly! Discover the rich history and stunning landscapes of Afghanistan."]],
    ["Should I go to Albania", ["Absolutely! Explore the beautiful coastlines and historical sites of Albania."]],
    ["Should I go to Algeria", ["Yes! Experience the diverse culture and landscapes of Algeria."]],
    ["Should I go to Andorra", ["Definitely! Enjoy the charming atmosphere and scenic beauty of Andorra."]],
    ["Should I go to Angola", ["For sure! Immerse yourself in the vibrant culture and natural wonders of Angola."]],
    ["Should I go to Antigua and Barbuda", ["Absolutely! Relax on the pristine beaches and soak up the Caribbean vibes of Antigua and Barbuda."]],
    ["Should I go to Argentina", ["Absolutely! Tango your way through the lively streets and breathtaking landscapes of Argentina."]],
    ["Should I go to Armenia", ["Yes! Explore the ancient history, stunning monasteries, and beautiful landscapes of Armenia."]],
    ["Should I go to Australia", ["Yes! Dive into the stunning beaches, unique wildlife, and vibrant cities of Australia."]],
    ["Should I go to Austria", ["Definitely! Explore the historic architecture, stunning landscapes, and delicious cuisine of Austria."]],
    ["Should I go to Azerbaijan", ["Certainly! Experience the blend of modernity and tradition in captivating Azerbaijan."]],
    ["Should I go to Bahamas", ["For sure! Relax on the pristine beaches and soak up the laid-back vibes of the Bahamas."]],
    ["Should I go to Bahrain", ["Absolutely! Immerse yourself in the rich culture, modern architecture, and warm hospitality of Bahrain."]],
    ["Should I go to Bangladesh", ["Yes! Discover the colorful culture, bustling cities, and lush landscapes of Bangladesh."]],
    ["Should I go to Barbados", ["Absolutely! Enjoy the laid-back Caribbean atmosphere, beautiful beaches, and friendly locals of Barbados."]],
    ["Should I go to Belarus", ["Definitely! Explore the fascinating history, vibrant culture, and beautiful countryside of Belarus."]],
    ["Should I go to Belgium", ["Certainly! Indulge in delicious chocolates, explore historic cities, and admire stunning architecture in Belgium."]],
    ["Should I go to Belize", ["For sure! Experience the lush jungles, ancient ruins, and vibrant marine life of Belize."]],
    ["Should I go to Benin", ["Absolutely! Discover the rich history, vibrant markets, and beautiful beaches of Benin."]],
    ["Should I go to Bhutan", ["Yes! Experience the unique culture, stunning Himalayan landscapes, and spiritual atmosphere of Bhutan."]],
    ["Should I go to Bolivia", ["Absolutely! Explore the diverse landscapes, rich culture, and colorful markets of Bolivia."]],
    ["Should I go to Bosnia and Herzegovina", ["Definitely! Discover the blend of cultures, charming old towns, and beautiful nature of Bosnia and Herzegovina."]],
    ["Should I go to Botswana", ["Certainly! Embark on thrilling safaris, explore the vast wilderness, and encounter incredible wildlife in Botswana."]],
    ["Should I go to Brazil", ["For sure! Experience the vibrant culture, stunning beaches, and breathtaking natural beauty of Brazil."]],
    ["Should I go to Brunei", ["Absolutely! Discover the rich culture, pristine rainforests, and stunning mosques of Brunei."]],
    ["Should I go to Bulgaria", ["Yes! Explore the rich history, picturesque landscapes, and vibrant cities of Bulgaria."]],
    ["Should I go to Burkina Faso", ["Definitely! Experience the colorful markets, diverse cultures, and beautiful landscapes of Burkina Faso."]],
    ["Should I go to Burundi", ["Certainly! Discover the beautiful scenery, friendly people, and unique culture of Burundi."]],
    ["Should I go to Cabo Verde", ["For sure! Enjoy the stunning beaches, vibrant culture, and relaxed atmosphere of Cabo Verde."]],
    ["Should I go to Cambodia", ["Absolutely! Explore the ancient temples of Angkor Wat, lush jungles, and vibrant markets of Cambodia."]],
    ["Should I go to Cameroon", ["Yes! Experience the diverse cultures, stunning landscapes, and abundant wildlife of Cameroon."]],
    ["Should I go to Canada", ["Definitely! Explore the breathtaking natural beauty, vibrant cities, and diverse culture of Canada."]],
    ["Should I go to Central African Republic", ["Certainly! Discover the rich wildlife, diverse landscapes, and vibrant culture of the Central African Republic."]],
    ["Should I go to Chad", ["For sure! Experience the vast desert landscapes, rich history, and unique cultures of Chad."]],
    ["Should I go to Chile", ["Absolutely! Explore the diverse landscapes, from the Atacama Desert to the glaciers of Patagonia, in Chile."]],
    ["Should I go to China", ["Yes! Experience the ancient history, modern cities, and diverse landscapes of China."]],
    ["Should I go to Colombia", ["Definitely! Immerse yourself in the vibrant culture, stunning landscapes, and friendly people of Colombia."]],
    ["Should I go to Comoros", ["Certainly! Relax on the beautiful beaches, explore volcanic landscapes, and experience the unique culture of Comoros."]],
    ["Should I go to Congo (Congo-Brazzaville)", ["For sure! Experience the rich biodiversity, vibrant culture, and stunning landscapes of Congo (Congo-Brazzaville)"]],
    ["Should I go to Costa Rica", ["Absolutely! Explore the lush rainforests, pristine beaches, and abundant wildlife of Costa Rica."]],
    ["Should I go to Croatia", ["Yes! Discover the stunning coastline, historic cities, and beautiful national parks of Croatia."]],
    ["Should I go to Cuba", ["Definitely! Experience the vibrant culture, colonial architecture, and beautiful beaches of Cuba."]],
    ["Should I go to Cyprus", ["Certainly! Relax on the beautiful beaches, explore ancient ruins, and enjoy delicious cuisine in Cyprus."]],
    ["Should I go to Czech Republic", ["For sure! Explore the charming cities, stunning castles, and picturesque landscapes of the Czech Republic."]],
    ["Should I go to Democratic Republic of the Congo (Congo-Kinshasa)", ["Absolutely! Experience the rich biodiversity, vibrant culture, and stunning landscapes of the Democratic Republic of the Congo (Congo-Kinshasa)."]],
    ["Should I go to Denmark", ["Yes! Explore the historic cities, charming countryside, and innovative design of Denmark."]],
    ["Should I go to Djibouti", ["Definitely! Experience the unique landscapes, rich culture, and warm hospitality of Djibouti."]],
    ["Should I go to Dominica", ["Certainly! Explore the lush rainforests, stunning waterfalls, and friendly culture of Dominica."]],
    ["Should I go to Dominican Republic", ["For sure! Relax on the beautiful beaches, explore colonial cities, and experience the vibrant culture of the Dominican Republic."]],
    ["Should I go to Ecuador", ["Absolutely! Explore the diverse landscapes, from the Amazon Rainforest to the Galápagos Islands, in Ecuador."]],
    ["Should I go to Egypt", ["Yes! Explore the ancient pyramids, vibrant bazaars, and stunning beaches of Egypt."]],
    ["Should I go to El Salvador", ["Definitely! Explore the charming colonial towns, beautiful beaches, and lush forests of El Salvador."]],
    ["Should I go to Equatorial Guinea", ["Certainly! Discover the diverse landscapes, rich culture, and unique wildlife of Equatorial Guinea."]],
    ["Should I go to Eritrea", ["For sure! Experience the unique architecture, rich history, and stunning landscapes of Eritrea."]],
    ["Should I go to Estonia", ["Absolutely! Explore the historic cities, beautiful islands, and scenic countryside of Estonia."]],
    ["Should I go to Eswatini (formerly Swaziland)", ["Yes! Discover the rich culture, stunning landscapes, and friendly people of Eswatini (formerly Swaziland)"]],
    ["Should I go to Ethiopia", ["Definitely! Experience the ancient history, diverse cultures, and stunning landscapes of Ethiopia."]],
    ["Should I go to Fiji", ["Certainly! Relax on the pristine beaches, dive into crystal-cls waters, and experience the warm hospitality of Fiji."]],
    ["Should I go to Finland", ["For sure! Explore the stunning natural beauty, vibrant cities, and unique culture of Finland."]],
    ["Should I go to France", ["Absolutely! Explore the romantic streets of Paris, indulge in exquisite cuisine, and discover charming villages in France."]],
    ["Should I go to Gabon", ["Yes! Experience the lush rainforests, diverse wildlife, and stunning beaches of Gabon."]],
    ["Should I go to Gambia", ["Definitely! Explore the vibrant markets, beautiful beaches, and rich culture of the Gambia."]],
    ["Should I go to Georgia", ["Certainly! Discover the ancient history, stunning landscapes, and warm hospitality of Georgia."]],
    ["Should I go to Germany", ["For sure! Explore the historic cities, picturesque landscapes, and vibrant culture of Germany."]],
    ["Should I go to Ghana", ["Absolutely! Experience the rich history, vibrant culture, and friendly people of Ghana."]],
    ["Should I go to Greece", ["Yes! Explore the ancient ruins, beautiful islands, and delicious cuisine of Greece."]],
    ["Should I go to Grenada", ["Definitely! Relax on the stunning beaches, explore lush rainforests, and experience the friendly culture of Grenada."]],
    ["Should I go to Guatemala", ["Certainly! Explore the ancient Mayan ruins, beautiful landscapes, and vibrant culture of Guatemala."]],
    ["Should I go to Guinea", ["For sure! Experience the diverse landscapes, vibrant markets, and rich culture of Guinea."]],
    ["Should I go to Guinea-Bissau", ["Absolutely! Explore the laid-back atmosphere, pristine beaches, and rich culture of Guinea-Bissau."]],
    ["Should I go to Guyana", ["Yes! Discover the pristine rainforests, diverse wildlife, and rich culture of Guyana."]],
    ["Should I go to Haiti", ["Definitely! Experience the vibrant culture, stunning beaches, and rich history of Haiti."]],
    ["Should I go to Honduras", ["Certainly! Explore the ancient ruins, beautiful beaches, and lush rainforests of Honduras."]],
    ["Should I go to Hungary", ["For sure! Discover the historic architecture, vibrant culture, and delicious cuisine of Hungary."]],
    ["Should I go to Iceland", ["Absolutely! Witness the awe-inspiring natural beauty, from majestic waterfalls to the Northern Lights, in Iceland."]],
    ["Should I go to India", ["Yes! Explore the diverse cultures, stunning landmarks, and vibrant festivals of India."]],
    ["Should I go to Indonesia", ["Definitely! Experience the rich culture, stunning landscapes, and diverse wildlife of Indonesia."]],
    ["Should I go to Iran", ["Certainly! Explore the ancient sites, vibrant bazaars, and warm hospitality of Iran."]],
    ["Should I go to Iraq", ["For sure! Experience the rich history, diverse cultures, and stunning landscapes of Iraq."]],
    ["Should I go to Ireland", ["Absolutely! Explore the lush green landscapes, charming villages, and vibrant cities of Ireland."]],
    ["Should I go to Israel", ["Yes! Explore the historic sites, vibrant markets, and diverse landscapes of Israel."]],
    ["Should I go to Italy", ["Definitely! Discover the rich history, art, and cuisine of beautiful Italy."]],
    ["Should I go to Jamaica", ["Certainly! Relax on the stunning beaches, experience the vibrant music scene, and explore lush rainforests in Jamaica."]],
    ["Should I go to Japan", ["For sure! Experience the blend of tradition and modernity, from ancient temples to bustling metropolises, in Japan."]],
    ["Should I go to Jordan", ["Absolutely! Explore the ancient ruins, stunning deserts, and warm hospitality of Jordan."]],
    ["Should I go to Kazakhstan", ["Yes! Discover the vast steppes, stunning mountains, and rich culture of Kazakhstan."]],
    ["Should I go to Kenya", ["Definitely! Embark on thrilling safaris, witness the Great Migration, and relax on beautiful beaches in Kenya."]],
    ["Should I go to Kiribati", ["Certainly! Experience the laid-back island lifestyle, pristine beaches, and rich culture of Kiribati."]],
    ["Should I go to Kosovo", ["For sure! Explore the historic landmarks, vibrant cities, and stunning landscapes of Kosovo."]],
    ["Should I go to Kuwait", ["Absolutely! Experience the modern architecture, rich culture, and warm hospitality of Kuwait."]],
    ["Should I go to Kyrgyzstan", ["Yes! Explore the stunning mountains, pristine lakes, and nomadic culture of Kyrgyzstan."]],
    ["Should I go to Laos", ["Definitely! Discover the serene temples, lush landscapes, and friendly locals of Laos."]],
    ["Should I go to Latvia", ["Certainly! Explore the charming old towns, beautiful beaches, and lush forests of Latvia."]],
    ["Should I go to Lebanon", ["For sure! Experience the vibrant nightlife, delicious cuisine, and rich history of Lebanon."]],
    ["Should I go to Lesotho", ["Absolutely! Explore the stunning mountain landscapes, traditional villages, and warm hospitality of Lesotho."]],
    ["Should I go to Liberia", ["Yes! Discover the rich history, vibrant culture, and stunning beaches of Liberia."]],
    ["Should I go to Libya", ["Definitely! Explore the ancient ruins, stunning desert landscapes, and warm hospitality of Libya."]],
    ["Should I go to Liechtenstein", ["Certainly! Experience the charming villages, stunning alpine scenery, and outdoor adventures of Liechtenstein."]],
    ["Should I go to Lithuania", ["For sure! Explore the historic cities, beautiful lakes, and vibrant culture of Lithuania."]],
    ["Should I go to Luxembourg", ["Absolutely! Discover the picturesque countryside, historic castles, and vibrant cities of Luxembourg."]],
    ["Should I go to Madagascar", ["Yes! Explore the unique wildlife, pristine beaches, and diverse landscapes of Madagascar."]],
    ["Should I go to Malawi", ["Definitely! Experience the warm hospitality, stunning landscapes, and diverse wildlife of Malawi."]],
    ["Should I go to Malaysia", ["Certainly! Explore the vibrant cities, stunning beaches, and lush rainforests of Malaysia."]],
    ["Should I go to Maldives", ["For sure! Relax in luxury resorts, snorkel in crystal-cls waters, and enjoy romantic sunsets in the Maldives."]],
    ["Should I go to Mali", ["Absolutely! Explore the ancient mud-brick mosques, vibrant markets, and diverse landscapes of Mali."]],
    ["Should I go to Malta", ["Yes! Discover the rich history, stunning architecture, and crystal-cls waters of Malta."]],
    ["Should I go to Marshall Islands", ["Definitely! Experience the laid-back island lifestyle, pristine beaches, and vibrant culture of the Marshall Islands."]],
    ["Should I go to Mauritania", ["Certainly! Explore the vast desert landscapes, ancient cities, and rich culture of Mauritania."]],
    ["Should I go to Mauritius", ["For sure! Relax on the beautiful beaches, explore lush forests, and experience the vibrant culture of Mauritius."]],
    ["Should I go to Mexico", ["Absolutely! Explore the ancient ruins, vibrant cities, and delicious cuisine of Mexico."]],
    ["Should I go to Micronesia", ["Yes! Experience the stunning coral reefs, pristine beaches, and unique culture of Micronesia."]],
    ["Should I go to Moldova", ["Definitely! Discover the historic landmarks, charming villages, and rich wine culture of Moldova."]],
    ["Should I go to Monaco", ["Certainly! Experience the glitz and glamour, beautiful coastline, and vibrant atmosphere of Monaco."]],
    ["Should I go to Mongolia", ["For sure! Explore the vast steppes, stunning landscapes, and nomadic culture of Mongolia."]],
    ["Should I go to Montenegro", ["Absolutely! Discover the picturesque coastline, historic towns, and stunning mountains of Montenegro."]],
    ["Should I go to Morocco", ["Yes! Explore the vibrant souks, ancient medinas, and stunning landscapes of Morocco."]],
    ["Should I go to Mozambique", ["Definitely! Relax on the pristine beaches, dive into colorful coral reefs, and explore vibrant markets in Mozambique."]],
    ["Should I go to Myanmar (Burma)", ["Certainly! Explore the ancient temples of Bagan, serene landscapes, and rich culture of Myanmar (Burma)."]],
    ["Should I go to Namibia", ["For sure! Experience the breathtaking landscapes, unique wildlife, and warm hospitality of Namibia."]],
    ["Should I go to Nauru", ["Absolutely! Experience the laid-back island lifestyle, pristine beaches, and friendly locals of Nauru."]],
    ["Should I go to Nepal", ["Yes! Trek in the Himalayas, explore ancient temples, and experience the rich culture of Nepal."]],
    ["Should I go to Netherlands", ["Definitely! Explore the picturesque canals, historic windmills, and vibrant cities of the Netherlands."]],
    ["Should I go to New Zealand", ["Certainly! Immerse yourself in stunning landscapes, thrilling adventures, and warm hospitality in New Zealand."]],
    ["Should I go to Nicaragua", ["For sure! Explore the colonial cities, pristine beaches, and lush rainforests of Nicaragua."]],
    ["Should I go to Niger", ["Absolutely! Experience the vast desert landscapes, vibrant markets, and rich culture of Niger."]],
    ["Should I go to Nigeria", ["Yes! Explore the bustling cities, diverse cultures, and vibrant nightlife of Nigeria."]],
    ["Should I go to North Korea", ["Definitely! Experience the unique culture, historic sites, and warm hospitality of North Korea."]],
    ["Should I go to North Macedonia", ["Certainly! Explore the historic landmarks, picturesque landscapes, and warm hospitality of North Macedonia."]],
    ["Should I go to Norway", ["For sure! Explore the stunning fjords, charming cities, and majestic mountains of Norway."]],
    ["Should I go to Oman", ["Absolutely! Experience the rich history, stunning desert landscapes, and warm hospitality of Oman."]],
    ["Should I go to Pakistan", ["Yes! Explore the ancient ruins, majestic mountains, and vibrant bazaars of Pakistan."]],
    ["Should I go to Palau", ["Definitely! Dive into crystal-cls waters, explore lush forests, and experience the rich culture of Palau."]],
    ["Should I go to Palestine", ["Certainly! Explore the historic landmarks, vibrant markets, and warm hospitality of Palestine."]],
    ["Should I go to Panama", ["For sure! Explore the Panama Canal, pristine beaches, and lush rainforests of Panama."]],
    ["Should I go to Papua New Guinea", ["Absolutely! Experience the diverse cultures, stunning landscapes, and unique wildlife of Papua New Guinea."]],
    ["Should I go to Paraguay", ["Yes! Explore the Jesuit ruins, vibrant markets, and beautiful landscapes of Paraguay."]],
    ["Should I go to Peru", ["Definitely! Explore the ancient ruins of Machu Picchu, vibrant markets, and stunning landscapes of Peru."]],
    ["Should I go to Philippines", ["Certainly! Relax on the beautiful beaches, dive into crystal-cls waters, and explore vibrant cities in the Philippines."]],
    ["Should I go to Poland", ["For sure! Discover the historic landmarks, charming old towns, and vibrant culture of Poland."]],
    ["Should I go to Portugal", ["Absolutely! Explore the historic cities, stunning beaches, and delicious cuisine of Portugal."]],
    ["Should I go to Qatar", ["Yes! Experience the modern skyline, rich cultural heritage, and warm hospitality of Qatar."]],
    ["Should I go to Romania", ["Definitely! Explore the medieval castles, charming villages, and breathtaking landscapes of Romania."]],
    ["Should I go to Russia", ["Certainly! Explore the historic landmarks, vibrant cities, and vast wilderness of Russia."]],
    ["Should I go to Rwanda", ["For sure! Explore the lush rainforests, encounter mountain gorillas, and experience the warm hospitality of Rwanda."]],
    ["Should I go to Saint Kitts and Nevis", ["Absolutely! Relax on the pristine beaches, explore lush rainforests, and experience the laid-back atmosphere of Saint Kitts and Nevis."]],
    ["Should I go to Saint Lucia", ["Yes! Relax on the stunning beaches, explore lush rainforests, and experience the vibrant culture of Saint Lucia."]],
    ["Should I go to Saint Vincent and the Grenadines", ["Definitely! Explore the beautiful beaches, vibrant marine life, and friendly culture of Saint Vincent and the Grenadines."]],
    ["Should I go to Samoa", ["Certainly! Experience the Polynesian culture, pristine beaches, and lush rainforests of Samoa."]],
    ["Should I go to San Marino", ["For sure! Explore the historic landmarks, charming streets, and stunning views of San Marino."]],
    ["Should I go to Sao Tome and Principe", ["Absolutely! Relax on the beautiful beaches, explore lush rainforests, and experience the laid-back atmosphere of Sao Tome and Principe."]],
    ["Should I go to Saudi Arabia", ["Yes! Experience the rich history, stunning deserts, and warm hospitality of Saudi Arabia."]],
    ["Should I go to Senegal", ["Definitely! Explore the vibrant markets, beautiful beaches, and rich culture of Senegal."]],
    ["Should I go to Serbia", ["Certainly! Explore the historic landmarks, vibrant cities, and warm hospitality of Serbia."]],
    ["Should I go to Seychelles", ["For sure! Relax on the pristine beaches, snorkel in crystal-cls waters, and explore lush forests in Seychelles."]],
    ["Should I go to Sierra Leone", ["Absolutely! Experience the beautiful beaches, vibrant culture, and warm hospitality of Sierra Leone."]],
    ["Should I go to Singapore", ["Yes! Explore the futuristic cityscape, delicious cuisine, and vibrant culture of Singapore."]],
    ["Should I go to Slovakia", ["Definitely! Explore the historic castles, charming towns, and stunning landscapes of Slovakia."]],
    ["Should I go to Slovenia", ["Certainly! Explore the picturesque landscapes, historic cities, and outdoor adventures of Slovenia."]],
    ["Should I go to Solomon Islands", ["For sure! Dive into crystal-cls waters, relax on pristine beaches, and experience the laid-back island lifestyle of the Solomon Islands."]],
    ["Should I go to Somalia", ["Absolutely! Experience the rich history, vibrant culture, and stunning landscapes of Somalia."]],
    ["Should I go to South Africa", ["Yes! Embark on thrilling safaris, explore vibrant cities, and relax on stunning beaches in South Africa."]],
    ["Should I go to South Korea", ["Definitely! Explore the dynamic cities, historic landmarks, and delicious cuisine of South Korea."]],
    ["Should I go to South Sudan", ["Certainly! Experience the rich culture, diverse landscapes, and warm hospitality of South Sudan."]],
    ["Should I go to Spain", ["For sure! Explore the historic landmarks, vibrant culture, and delicious cuisine of Spain."]],
    ["Should I go to Sri Lanka", ["Absolutely! Explore the ancient ruins, lush tea plantations, and stunning beaches of Sri Lanka."]],
    ["Should I go to Sudan", ["Yes! Experience the ancient pyramids, vibrant markets, and diverse landscapes of Sudan."]],
    ["Should I go to Suriname", ["Definitely! Explore the diverse cultures, pristine rainforests, and vibrant markets of Suriname."]],
    ["Should I go to Sweden", ["Certainly! Explore the picturesque landscapes, vibrant cities, and outdoor adventures of Sweden."]],
    ["Should I go to Switzerland", ["For sure! Explore the stunning alpine scenery, charming villages, and outdoor adventures of Switzerland."]],
    ["Should I go to Syria", ["Absolutely! Experience the rich history, vibrant markets, and warm hospitality of Syria."]],
    ["Should I go to Taiwan", ["Yes! Explore the bustling cities, stunning natural landscapes, and vibrant culture of Taiwan."]],
    ["Should I go to Tajikistan", ["Definitely! Discover the stunning mountains, ancient fortresses, and warm hospitality of Tajikistan."]],
    ["Should I go to Tanzania", ["Certainly! Embark on thrilling safaris, climb Mount Kilimanjaro, and relax on beautiful beaches in Tanzania."]],
    ["Should I go to Thailand", ["For sure! Explore the vibrant street life, ancient temples, and pristine beaches of Thailand."]],
    ["Should I go to Timor-Leste", ["Absolutely! Experience the rich culture, stunning landscapes, and warm hospitality of Timor-Leste."]],
    ["Should I go to Togo", ["Yes! Explore the vibrant markets, beautiful beaches, and rich culture of Togo."]],
    ["Should I go to Tonga", ["Definitely! Experience the laid-back island lifestyle, pristine beaches, and vibrant culture of Tonga."]],
    ["Should I go to Trinidad and Tobago", ["Certainly! Relax on the stunning beaches, experience the vibrant culture, and enjoy the delicious cuisine of Trinidad and Tobago."]],
    ["Should I go to Tunisia", ["For sure! Explore the ancient ruins, vibrant markets, and beautiful beaches of Tunisia."]],
    ["Should I go to Turkey", ["Absolutely! Explore the historic landmarks, vibrant bazaars, and stunning landscapes of Turkey."]],
    ["Should I go to Turkmenistan", ["Yes! Discover the ancient Silk Road cities, unique landscapes, and warm hospitality of Turkmenistan."]],
    ["Should I go to Tuvalu", ["Definitely! Experience the laid-back island lifestyle, pristine beaches, and warm hospitality of Tuvalu."]],
    ["Should I go to Uganda", ["Certainly! Explore the diverse wildlife, stunning landscapes, and warm hospitality of Uganda."]],
    ["Should I go to Ukraine", ["For sure! Explore the historic landmarks, vibrant cities, and rich cultural heritage of Ukraine."]],
    ["Should I go to United Arab Emirates", ["Absolutely! Experience the modern skyscrapers, luxurious shopping, and rich culture of the United Arab Emirates."]],
    ["Should I go to United Kingdom", ["Yes! Explore the historic landmarks, charming countryside, and vibrant cities of the United Kingdom."]],
    ["Should I go to United States", ["Definitely! Explore the diverse landscapes, iconic landmarks, and vibrant cities of the United States."]],
    ["Should I go to Uruguay", ["Certainly! Relax on the beautiful beaches, explore charming colonial towns, and experience the vibrant culture of Uruguay."]],
    ["Should I go to Uzbekistan", ["For sure! Discover the historic cities along the Silk Road, stunning mosques, and rich cultural heritage of Uzbekistan."]],
    ["Should I go to Vanuatu", ["Absolutely! Experience the laid-back island lifestyle, pristine beaches, and vibrant culture of Vanuatu."]],
    ["Should I go to Vatican City", ["Yes! Explore the historic landmarks, stunning art, and spiritual atmosphere of Vatican City."]],
    ["Should I go to Venezuela", ["Definitely! Explore the stunning landscapes, diverse wildlife, and rich culture of Venezuela."]],
    ["Should I go to Vietnam", ["Certainly! Explore the bustling cities, ancient temples, and stunning landscapes of Vietnam."]],
    ["Should I go to Yemen", ["For sure! Experience the rich history, unique architecture, and warm hospitality of Yemen."]],
    ["Should I go to Zambia", ["Absolutely! Embark on thrilling safaris, witness the majestic Victoria Falls, and experience the warm hospitality of Zambia."]],
    ["Should I go to Zimbabwe", ["Yes! Explore the stunning landscapes, rich wildlife, and vibrant culture of Zimbabwe."]]
]


if __name__ == '__main__':
    chat = Chat(pairs, reflections)
    chat.converse()